# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: postgres-config
#   namespace: consumer
#   labels:
#     app: postgres-config
# data:
#   POSTGRES_DB: "cve"
#   POSTGRES_USER: "postgres"
#   POSTGRES_PASSWORD: "postgres"
#   PG_DATA: /data
#   host: "postgres.consumer"
#   port: "5432"

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: consumer
  labels:
    app: postgres-config
data:
  POSTGRES_DB: "{{ .Values.postgres.dbname }}"
  POSTGRES_USER: "{{ .Values.postgres.user }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
  PG_DATA: /data
  host: "{{ .Values.postgres.host }}"
  port: "{{ .Values.postgres.port }}"