apiVersion: apps/v1
kind: Deployment
metadata:
  name: cve-consumer
  namespace: consumer
  labels:
    app: cve-consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cve-consumer
  template:
    metadata:
      labels:
        app: cve-consumer
    spec:
      imagePullSecrets:
      - name: regcred
      initContainers:
      - name: flyway-init
        image: "{{ .Values.image.docker_repo }}:{{ .Values.image.pg_container }}-{{ .Values.image.pg_container_version }}"
        imagePullPolicy: Always
        command:
        - "/bin/sh"
        - "-c"
        - "flyway -user={{ .Values.postgres.user }} -password={{ .Values.postgres.password }} -url={{ .Values.postgres.url }} migrate"
      containers:
      - name: cve-consumer
        image: "maheshpoojaryneu/csye7125:webapp-consumer"
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKERS
          value: "{{ .Values.broker }}"
        - name: KAFKA_TOPIC
          value: "push_cve_records"
        - name: POSTGRES_DSN
          value: "host={{ .Values.postgres.host }} user={{ .Values.postgres.user }} password={{ .Values.postgres.password }} dbname=cve port=5432 sslmode=disable"
<<<<<<< HEAD
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
          subPath: check_kafka_topic.sh
          readOnly: true
        readinessProbe:
          exec:
          command:
            - /bin/sh
            - /scripts/check_kafka_topic.sh
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - ps aux | grep ./webapp-consumer
          initialDelaySeconds: 15  
          periodSeconds: 10       
          timeoutSeconds: 5      
          failureThreshold: 3  
      volumes:
      - name: script-volume
        configMap:
          name: postgres-config
          items:
            - key: check_kafka_topic.sh
              path: check_kafka_topic.sh
=======

>>>>>>> 44d473ebce989f8825a8aa80ed338b0e7c86c6eb
