apiVersion: apps/v1
kind: Deployment
metadata:
  name: cve-consumer
  namespace: consumer
  labels:
    app: cve-consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cve-consumer
  template:
    metadata:
      labels:
        app: cve-consumer
    spec:
      imagePullSecrets:
      - name: regcred
      initContainers:
      - name: flyway-init
        image: "{{ .Values.image.docker_repo }}:{{ .Values.image.pg_container }}-{{ .Values.image.pg_container_version }}"
        imagePullPolicy: Always
        command:
        - "/bin/sh"
        - "-c"
        - "flyway -user={{ .Values.postgres.user }} -password={{ .Values.postgres.password }} -url={{ .Values.postgres.url }} migrate"
      containers:
      - name: cve-consumer
        image: "maheshpoojaryneu/csye7125:webapp-consumer"
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKERS
          value: "{{ .Values.broker }}"
        - name: KAFKA_TOPIC
          value: "push_cve_records"
        - name: POSTGRES_DSN
          value: "host={{ .Values.postgres.host }} user={{ .Values.postgres.user }} password={{ .Values.postgres.password }} dbname=cve port=5432 sslmode=disable"

